version: '3.8'

networks:
  internal:
    name: '${COMPOSE_PROJECT_NAME}__internal_network'

services:
  mir_of_books_service:
    image: '${COMPOSE_PROJECT_NAME}_backend:latest'
    container_name: '${COMPOSE_PROJECT_NAME}__backend'
    command: ['yarn', 'start:dev']
    ports:
      - '${PORT_BACKEND}:${PORT_BACKEND}'
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - ./.env:/app/.env
    networks:
      - internal
    environment:
      VERSION_TAG: '${VERSION_TAG}'

  postgres:
    image: 'postgres:alpine'
    container_name: '${COMPOSE_PROJECT_NAME}__postgres'
    networks:
      - internal
    environment:
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
      POSTGRES_USER: '${DATABASE_USER}'
      POSTGRES_DB: '${DATABASE_NAME}'

  pgadmin:
    image: 'dpage/pgadmin4:latest'
    container_name: '${COMPOSE_PROJECT_NAME}__pgadmin'
    ports:
      - '${PORT_PGADMIN}:${PORT_PGADMIN}'
    networks:
      - internal
    environment:
      PGADMIN_DEFAULT_EMAIL: '${PGADMIN_EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_PASSWORD}'
