version: '3.8'

networks:
  internal:
    name: '${COMPOSE_PROJECT_NAME}__internal_network'

services:
  mir_of_books_service:
    image: '${COMPOSE_PROJECT_NAME}_backend:latest'
    container_name: '${COMPOSE_PROJECT_NAME}__backend'
    command: ['yarn', 'start:dev']
    ports:
      - '${PORT_BACKEND}:${PORT_BACKEND}'
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - ./.env:/app/.env
    networks:
      - internal
    environment:
      VERSION_TAG: '${VERSION_TAG}'

  database:
    image: 'mongo'
    container_name: '${COMPOSE_PROJECT_NAME}__database'
    networks:
      - internal
    environment:
      MONGO_INITDB_ROOT_PASSWORD: '${DATABASE_PASSWORD}'
      MONGO_INITDB_ROOT_USERNAME: '${DATABASE_USER}'
      MONGO_INITDB_DATABASE: '${DATABASE_NAME}'

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '${DB_ADMIN_PORT}:${DB_ADMIN_PORT}'
    networks:
      - internal
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: '${DB_ADMIN_EMAIL}'
      ME_CONFIG_MONGODB_ADMINPASSWORD: '${DB_ADMIN_PASSWORD}'
      ME_CONFIG_MONGODB_URL: 'mongodb://${DATABASE_USER}:${DATABASE_PASSWORD}@mongo:/${DATABASE_PORT}'